# Generated by Django 4.0 on 2021-12-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='data',
            field=models.TimeField(auto_now=True),
        ),
    ]
