# Generated by Django 4.0 on 2021-12-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cliente_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
