# Generated by Django 4.0 on 2021-12-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_cliente_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(choices=[(1, 'Pago'), (0, 'Devendo')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
